
import { ModuleDefinition, ModuleTier, Tenant } from '../types';

export const MODULE_CATEGORIES = [
  {
    id: 'industry_vertical',
    label: 'Industry Kits',
    icon: 'Briefcase',
    description: 'Drop-in workflow packs tailored for healthcare, agriculture, e-commerce, retail, cold chain, and construction.',
    color: 'bg-blue-50 text-blue-700 border-blue-100'
  },
  {
    id: 'ai_feature',
    label: 'AI & Intelligence',
    icon: 'Brain',
    description: 'Route optimization, demand forecasting, and dispatch automation powered by real ML models.',
    color: 'bg-violet-50 text-violet-700 border-violet-100'
  },
  {
    id: 'integration',
    label: 'Integrations',
    icon: 'Plug',
    description: 'Connect your ERP (Frappe, SAP), accounting (QuickBooks), storefront (Shopify), and payment systems (M-Pesa, Stripe).',
    color: 'bg-emerald-50 text-emerald-700 border-emerald-100'
  },
  {
    id: 'addon',
    label: 'Productivity Add-ons',
    icon: 'Puzzle',
    description: 'White-label customer portals, driver app upgrades, and power-user features that extend your core stack.',
    color: 'bg-amber-50 text-amber-700 border-amber-100'
  },
  {
    id: 'compliance',
    label: 'Compliance & Audit',
    icon: 'ShieldCheck',
    description: 'GDPR data rights toolkit, ISO 28000 supply chain security audits, and regulatory reporting dashboards.',
    color: 'bg-rose-50 text-rose-700 border-rose-100'
  }
];

export const CORE_MODULES: ModuleDefinition[] = [
  {
    id: 'core-dashboard',
    name: 'Unified Dashboard',
    slug: 'dashboard',
    description: 'Central command centre for logistics operations.',
    category: 'core',
    tier: 'free',
    version: '2.4.0',
    versions: [{ version: '2.4.0', releaseDate: new Date().toISOString(), changelog: 'Initial stable release of the unified dashboard.' }],
    icon: 'LayoutDashboard',
    tags: ['core', 'visibility'],
    publisher: { id: 'shipstack', name: 'Shipstack Core', verified: true },
    pricing: { model: 'free' },
    dependencies: [],
    conflicts: [],
    permissionScope: { requiredPermissions: ['dashboard:view'], grantedPermissions: ['dashboard:view', 'dashboard:export'] },
    routes: ['/admin/dashboard'],
    isCore: true,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    hooks: {}
  },
  {
    id: 'core-dispatch',
    name: 'Smart Dispatch',
    slug: 'dispatch',
    description: 'Live assignment and routing engine.',
    category: 'core',
    tier: 'free',
    version: '1.8.2',
    versions: [{ version: '1.8.2', releaseDate: new Date().toISOString(), changelog: 'Optimized dispatch grid performance.' }],
    icon: 'Zap',
    tags: ['core', 'operations'],
    publisher: { id: 'shipstack', name: 'Shipstack Core', verified: true },
    pricing: { model: 'free' },
    dependencies: [],
    conflicts: [],
    permissionScope: { requiredPermissions: ['dispatch:view'], grantedPermissions: ['dispatch:view', 'dispatch:manage', 'dispatch:assign'] },
    routes: ['/admin/dispatch'],
    isCore: true,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    hooks: {}
  },
  {
    id: 'core-fleet',
    name: 'Fleet Control',
    slug: 'fleet',
    description: 'Vehicle lifecycle and maintenance tracking.',
    category: 'core',
    tier: 'free',
    version: '1.0.0',
    versions: [{ version: '1.0.0', releaseDate: new Date().toISOString(), changelog: 'Fleet management module launch.' }],
    icon: 'Truck',
    tags: ['core', 'assets'],
    publisher: { id: 'shipstack', name: 'Shipstack Core', verified: true },
    pricing: { model: 'free' },
    dependencies: [],
    conflicts: [],
    permissionScope: { requiredPermissions: ['fleet:view'], grantedPermissions: ['fleet:view', 'fleet:manage', 'fleet:all'] },
    routes: ['/admin/fleet'],
    isCore: true,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    hooks: {}
  },
  {
    id: 'core-trips',
    name: 'Trip Lifecycle',
    slug: 'trips',
    description: 'End-to-end trip execution and telemetry.',
    category: 'core',
    tier: 'free',
    version: '3.1.0',
    versions: [{ version: '3.1.0', releaseDate: new Date().toISOString(), changelog: 'Advanced telemetry support.' }],
    icon: 'Navigation',
    tags: ['core', 'tracking'],
    publisher: { id: 'shipstack', name: 'Shipstack Core', verified: true },
    pricing: { model: 'free' },
    dependencies: [],
    conflicts: [],
    permissionScope: { requiredPermissions: ['trips:view'], grantedPermissions: ['trips:view', 'trips:create', 'trips:edit', 'trips:assign'] },
    routes: ['/admin/trips'],
    isCore: true,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    hooks: {}
  },
  {
    id: 'core-invoicing',
    name: 'Financial Engine',
    slug: 'invoicing',
    description: 'Automated billing and revenue recognition.',
    category: 'core',
    tier: 'free',
    version: '1.2.0',
    versions: [{ version: '1.2.0', releaseDate: new Date().toISOString(), changelog: 'Support for multi-currency invoicing.' }],
    icon: 'DollarSign',
    tags: ['core', 'finance'],
    publisher: { id: 'shipstack', name: 'Shipstack Core', verified: true },
    pricing: { model: 'free' },
    dependencies: [],
    conflicts: [],
    permissionScope: { requiredPermissions: ['finance:view'], grantedPermissions: ['finance:view', 'finance:manage', 'invoicing:view', 'invoicing:all'] },
    routes: ['/admin/invoicing'],
    isCore: true,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    hooks: {}
  }
];

export const MARKETPLACE_MODULES: ModuleDefinition[] = [
  {
    id: 'vertical-healthcare',
    name: 'Medical Logistics Pro',
    slug: 'healthcare',
    description: 'Cold chain compliance and pharmaceutical grade handling.',
    category: 'industry_vertical',
    tier: 'professional',
    version: '1.0.5',
    versions: [{ version: '1.0.0', releaseDate: '2025-12-01', changelog: 'Initial medical module release.' }],
    icon: 'Stethoscope',
    tags: ['medical', 'compliance', 'cold-chain'],
    publisher: { id: 'shipstack', name: 'Shipstack Labs', verified: true },
    pricing: { model: 'flat', amount: 149, currency: 'USD', billingPeriod: 'monthly' },
    dependencies: [],
    conflicts: ['vertical-agriculture'],
    permissionScope: { requiredPermissions: ['dashboard:view'], grantedPermissions: ['exceptions:view', 'tracking:view'] },
    routes: ['/admin/vertical/medical'],
    status: 'active',
    createdAt: '2025-12-01T00:00:00Z',
    updatedAt: new Date().toISOString(),
    hooks: {}
  },
  {
    id: 'vertical-agriculture',
    name: 'Agri-Supply Network',
    slug: 'agriculture',
    description: 'Farm-to-market visibility and harvest yield logistics.',
    category: 'industry_vertical',
    tier: 'professional',
    version: '1.2.0',
    versions: [{ version: '1.0.0', releaseDate: '2026-01-10', changelog: 'Agriculture module launch.' }],
    icon: 'Sprout',
    tags: ['agriculture', 'freshness', 'farm'],
    publisher: { id: 'shipstack', name: 'Shipstack Labs', verified: true },
    pricing: { model: 'flat', amount: 149, currency: 'USD', billingPeriod: 'monthly' },
    dependencies: [],
    conflicts: ['vertical-healthcare'],
    permissionScope: { requiredPermissions: ['dashboard:view'], grantedPermissions: ['tracking:view'] },
    routes: ['/admin/vertical/agriculture'],
    status: 'active',
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: new Date().toISOString(),
    hooks: {}
  },
  {
    id: 'vertical-ecommerce',
    name: 'E-commerce Last Mile',
    slug: 'ecommerce',
    description: 'Hyper-local delivery optimization and courier network management.',
    category: 'industry_vertical',
    tier: 'starter',
    version: '2.0.1',
    versions: [{ version: '2.0.0', releaseDate: '2026-02-15', changelog: 'Rebuilt for high volume.' }],
    icon: 'ShoppingBag',
    tags: ['retail', 'speed', 'hyper-local'],
    publisher: { id: 'shipstack', name: 'Shipstack Core', verified: true },
    pricing: { model: 'flat', amount: 79, currency: 'USD', billingPeriod: 'monthly' },
    dependencies: [],
    conflicts: [],
    permissionScope: { requiredPermissions: ['dashboard:view'], grantedPermissions: ['orders:create'] },
    routes: ['/admin/vertical/ecommerce'],
    status: 'active',
    createdAt: '2026-02-15T00:00:00Z',
    updatedAt: new Date().toISOString(),
    hooks: {}
  },
  {
    id: 'vertical-retail',
    name: 'Retail Distribution',
    slug: 'retail',
    description: 'Store replenishment and omnichannel fulfillment.',
    category: 'industry_vertical',
    tier: 'starter',
    version: '1.1.0',
    versions: [],
    icon: 'Archive',
    tags: ['retail', 'warehouse', 'inventory'],
    publisher: { id: 'shipstack', name: 'Shipstack Core', verified: true },
    pricing: { model: 'flat', amount: 79, currency: 'USD', billingPeriod: 'monthly' },
    dependencies: [],
    conflicts: [],
    permissionScope: { requiredPermissions: ['dashboard:view'], grantedPermissions: ['warehouse:view'] },
    routes: ['/admin/vertical/retail'],
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    hooks: {}
  },
  {
    id: 'vertical-coldchain',
    name: 'Cold Chain Guardian',
    slug: 'coldchain',
    description: 'Real-time temperature monitoring and integrity reporting.',
    category: 'industry_vertical',
    tier: 'enterprise',
    version: '1.0.0',
    versions: [],
    icon: 'Flame',
    tags: ['temp-control', 'iot', 'sensors'],
    publisher: { id: 'iot-partner', name: 'ColdSense IoT', verified: true },
    pricing: { model: 'flat', amount: 299, currency: 'USD', billingPeriod: 'monthly' },
    dependencies: [],
    conflicts: [],
    permissionScope: { requiredPermissions: ['analytics:view'], grantedPermissions: ['analytics:all'] },
    routes: ['/admin/vertical/coldchain'],
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    hooks: {}
  },
  {
    id: 'vertical-construction',
    name: 'Heavy Materials Ops',
    slug: 'construction',
    description: 'Bulk material dispatch and construction site coordinate tracking.',
    category: 'industry_vertical',
    tier: 'enterprise',
    version: '0.9.0',
    versions: [],
    icon: 'Scale',
    tags: ['bulk', 'construction', 'heavy-load'],
    publisher: { id: 'raw-materials', name: 'BuildLogix', verified: false },
    pricing: { model: 'flat', amount: 299, currency: 'USD', billingPeriod: 'monthly' },
    dependencies: [],
    conflicts: [],
    permissionScope: { requiredPermissions: ['fleet:manage'], grantedPermissions: ['fleet:all'] },
    routes: ['/admin/vertical/construction'],
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    hooks: {}
  },
  {
    id: 'addon-cortex-ai',
    name: 'Cortex AI Optimizer',
    slug: 'cortex-ai',
    description: 'ML-driven delay prediction and automated resource allocation.',
    category: 'ai_feature',
    tier: 'professional',
    version: '2.5.0',
    versions: [],
    icon: 'Zap',
    tags: ['ai', 'optimization', 'ml'],
    publisher: { id: 'shipstack', name: 'Shipstack Labs', verified: true },
    pricing: { model: 'flat', amount: 199, currency: 'USD', billingPeriod: 'monthly' },
    dependencies: ['core-dispatch'],
    conflicts: [],
    permissionScope: { requiredPermissions: ['dispatch:manage'], grantedPermissions: ['analytics:view'] },
    routes: [],
    isFeatured: true,
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    hooks: {}
  },
  {
    id: 'addon-advanced-analytics',
    name: 'Insight Hub Pro',
    slug: 'advanced-analytics',
    description: 'Deep-dive reporting and custom BI dashboarding.',
    category: 'addon',
    tier: 'professional',
    version: '1.4.2',
    versions: [],
    icon: 'Activity',
    tags: ['analytics', 'bi', 'data'],
    publisher: { id: 'shipstack', name: 'Shipstack Core', verified: true },
    pricing: { model: 'flat', amount: 99, currency: 'USD', billingPeriod: 'monthly' },
    dependencies: [],
    conflicts: [],
    permissionScope: { requiredPermissions: ['analytics:view'], grantedPermissions: ['analytics:all', 'analytics:export'] },
    routes: ['/admin/analytics/pro'],
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    hooks: {}
  },
  {
    id: 'addon-route-optimizer',
    name: 'Route Wizard',
    slug: 'route-optimizer',
    description: 'Multi-stop TSP solver for urban delivery routes.',
    category: 'addon',
    tier: 'starter',
    version: '1.0.0',
    versions: [],
    icon: 'RouteIcon',
    tags: ['routing', 'speed', 'optimization'],
    publisher: { id: 'shipstack', name: 'Shipstack Core', verified: true },
    pricing: { model: 'flat', amount: 49, currency: 'USD', billingPeriod: 'monthly' },
    dependencies: ['core-dispatch'],
    conflicts: [],
    permissionScope: { requiredPermissions: ['dispatch:assign'], grantedPermissions: ['dispatch:manage'] },
    routes: [],
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    hooks: {}
  },
  {
    id: 'addon-customer-portal',
    name: 'White-Label Portal',
    slug: 'customer-portal',
    description: 'Your own branded tracking and ordering interface for clients.',
    category: 'addon',
    tier: 'starter',
    version: '1.2.0',
    versions: [],
    icon: 'Pin',
    tags: ['portal', 'branding', 'customers'],
    publisher: { id: 'shipstack', name: 'Shipstack Core', verified: true },
    pricing: { model: 'flat', amount: 29, currency: 'USD', billingPeriod: 'monthly' },
    dependencies: [],
    conflicts: [],
    permissionScope: { requiredPermissions: ['orders:view'], grantedPermissions: ['users:invite'] },
    routes: ['/portal/config'],
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    hooks: {}
  },
  {
    id: 'addon-driver-app-pro',
    name: 'Driver App Pro',
    slug: 'driver-app-pro',
    description: 'Offline support, barcode scanning, and multi-language for drivers.',
    category: 'addon',
    tier: 'professional',
    version: '2.0.0',
    versions: [],
    icon: 'Truck',
    tags: ['driver', 'offline', 'scanning'],
    publisher: { id: 'shipstack', name: 'Shipstack Core', verified: true },
    pricing: { model: 'flat', amount: 79, currency: 'USD', billingPeriod: 'monthly' },
    dependencies: ['core-trips'],
    conflicts: [],
    permissionScope: { requiredPermissions: ['trips:view'], grantedPermissions: ['trips:edit'] },
    routes: [],
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    hooks: {}
  },
  {
    id: 'integration-frappe-erp',
    name: 'Frappe / ERPNext Hub',
    slug: 'frappe-erp',
    description: 'Two-way sync for sales orders, delivery notes, and stock levels.',
    category: 'integration',
    tier: 'professional',
    version: '3.1.2',
    versions: [],
    icon: 'RefreshCw',
    tags: ['erp', 'sync', 'automation'],
    publisher: { id: 'frappe-partners', name: 'Frappe Certified', verified: true },
    pricing: { model: 'flat', amount: 99, currency: 'USD', billingPeriod: 'monthly' },
    dependencies: [],
    conflicts: [],
    permissionScope: { requiredPermissions: ['data_ingress:view'], grantedPermissions: ['data_ingress:manage'] },
    routes: ['/admin/ingress/frappe'],
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    hooks: {}
  },
  {
    id: 'integration-quickbooks',
    name: 'QuickBooks Sync',
    slug: 'quickbooks',
    description: 'Automatic invoice generation and payment reconciliation.',
    category: 'integration',
    tier: 'starter',
    version: '1.0.1',
    versions: [],
    icon: 'CheckCircle',
    tags: ['accounting', 'finance', 'sync'],
    publisher: { id: 'intuit', name: 'Intuit Marketplace', verified: true },
    pricing: { model: 'flat', amount: 39, currency: 'USD', billingPeriod: 'monthly' },
    dependencies: ['core-invoicing'],
    conflicts: [],
    permissionScope: { requiredPermissions: ['finance:view'], grantedPermissions: ['finance:manage'] },
    routes: ['/admin/finance/quickbooks'],
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    hooks: {}
  },
  {
    id: 'integration-shopify',
    name: 'Shopify Connector',
    slug: 'shopify',
    description: 'Fulfill Shopify orders directly within the Shipstack grid.',
    category: 'integration',
    tier: 'starter',
    version: '2.1.0',
    versions: [],
    icon: 'Package',
    tags: ['e-commerce', 'orders', 'sync'],
    publisher: { id: 'shopify', name: 'Shopify Partners', verified: true },
    pricing: { model: 'flat', amount: 39, currency: 'USD', billingPeriod: 'monthly' },
    dependencies: [],
    conflicts: [],
    permissionScope: { requiredPermissions: ['orders:view'], grantedPermissions: ['orders:create'] },
    routes: ['/admin/ingress/shopify'],
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    hooks: {}
  },
  {
    id: 'integration-mpesa',
    name: 'M-Pesa Gateway',
    slug: 'mpesa',
    description: 'Direct STK push for driver collections and B2C disbursements.',
    category: 'integration',
    tier: 'free',
    version: '2.0.0',
    versions: [],
    icon: 'Zap',
    tags: ['payments', 'kenya', 'mobile-money'],
    publisher: { id: 'safaricom', name: 'Safaricom Open API', verified: true },
    pricing: { model: 'free' },
    dependencies: [],
    conflicts: [],
    permissionScope: { requiredPermissions: ['finance:view'], grantedPermissions: ['finance:manage'] },
    routes: ['/admin/finance/mpesa'],
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    hooks: {}
  },
  {
    id: 'integration-stripe',
    name: 'Stripe Payments',
    slug: 'stripe',
    description: 'Accept credit card payments for enterprise invoices globally.',
    category: 'integration',
    tier: 'free',
    version: '1.0.0',
    versions: [],
    icon: 'DollarSign',
    tags: ['payments', 'global', 'card'],
    publisher: { id: 'stripe', name: 'Stripe Partners', verified: true },
    pricing: { model: 'free' },
    dependencies: [],
    conflicts: [],
    permissionScope: { requiredPermissions: ['finance:view'], grantedPermissions: ['finance:manage'] },
    routes: ['/admin/finance/stripe'],
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    hooks: {}
  },
  {
    id: 'compliance-gdpr-toolkit',
    name: 'GDPR Compliance Kit',
    slug: 'gdpr',
    description: 'Automated data deletion, PII masking, and consent management.',
    category: 'compliance',
    tier: 'professional',
    version: '1.0.0',
    versions: [],
    icon: 'ShieldCheck',
    tags: ['privacy', 'eu', 'security'],
    publisher: { id: 'shipstack', name: 'Shipstack Core', verified: true },
    pricing: { model: 'flat', amount: 79, currency: 'USD', billingPeriod: 'monthly' },
    dependencies: [],
    conflicts: [],
    permissionScope: { requiredPermissions: ['audit:view'], grantedPermissions: ['users:edit'] },
    routes: ['/admin/security/gdpr'],
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    hooks: {}
  },
  {
    id: 'compliance-iso-28000',
    name: 'ISO 28000 Auditor',
    slug: 'iso-28000',
    description: 'Supply chain security management system certification tooling.',
    category: 'compliance',
    tier: 'enterprise',
    version: '1.0.0',
    versions: [],
    icon: 'Scale',
    tags: ['iso', 'security', 'audit'],
    publisher: { id: 'compliance-experts', name: 'SafeOps Global', verified: true },
    pricing: { model: 'flat', amount: 199, currency: 'USD', billingPeriod: 'monthly' },
    dependencies: [],
    conflicts: [],
    permissionScope: { requiredPermissions: ['audit:view'], grantedPermissions: ['audit:export'] },
    routes: ['/admin/security/iso'],
    status: 'active',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    hooks: {}
  }
];

export const MODULE_LIFECYCLE_RULES = {
  maxTrialExtensions: 1,
  autoSuspendAfterDays: 3,
  deprecationNoticeDays: 90,
  requiredReviewForPublish: true,
  maxModulesPerTier: {
    free: 2,
    starter: 3,
    growth: 5,
    professional: 10,
    scale: 20,
    enterprise: 'unlimited'
  }
};

export const getModuleById = (id: string): ModuleDefinition | undefined => {
  return [...CORE_MODULES, ...MARKETPLACE_MODULES].find(m => m.id === id || m.slug === id);
};

export const getModulesForTier = (tier: Tenant['plan']): ModuleDefinition[] => {
  const tiers: Record<string, number> = { 'STARTER': 1, 'GROWTH': 2, 'SCALE': 3, 'ENTERPRISE': 4 };
  const currentTierRank = tiers[tier] || 0;
  
  return MARKETPLACE_MODULES.filter(m => {
    const moduleTierRank = tiers[m.tier.toUpperCase()] || 0;
    return moduleTierRank <= currentTierRank;
  });
};

export const checkModuleDependencies = (moduleId: string, installedModules: string[]): { canInstall: boolean; missing: string[] } => {
  const module = getModuleById(moduleId);
  if (!module) return { canInstall: false, missing: [] };
  
  const missing = module.dependencies
    .filter(dep => !installedModules.includes(dep.moduleId))
    .map(dep => dep.moduleId);
    
  return {
    canInstall: missing.length === 0,
    missing
  };
};

export const checkModuleConflicts = (moduleId: string, installedModules: string[]): { hasConflict: boolean; conflicting: string[] } => {
  const module = getModuleById(moduleId);
  if (!module) return { hasConflict: false, conflicting: [] };
  
  const conflicting = module.conflicts.filter(conflictId => installedModules.includes(conflictId));
  
  return {
    hasConflict: conflicting.length > 0,
    conflicting
  };
};

export const getModuleUpgradePath = (currentVersion: string, module: ModuleDefinition): string | null => {
  const currentIndex = module.versions.findIndex(v => v.version === currentVersion);
  if (currentIndex === -1 || currentIndex === module.versions.length - 1) return null;
  return module.versions[currentIndex + 1].version;
};
